version: "3"
services:
  database:
    image: postgres
    container_name: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  googliapparatus:
    image: dolandrew/googliapparatus
    container_name: "googliapparatus"
    ports:
      - "8080:8080"

  googli-ui:
    image: dolandrew/googli-ui
    container_name: "googli-ui"
    ports:
      - "3000:3000"