version: "3"
services:
  database:
    image: postgres
    container_name: "postgres_googli"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - googliapparatus_default

networks:
  googliapparatus_default: